os: linux
language: node_js

node_js:
  - 'lts/*'

jobs:
  include:
    - stage: release
      script:
        - npm test
      after_success:
        - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - node_modules
